
-- Final CRM Schema Definition Script
-- Version: 3.2
-- Description: This script creates the complete database schema for the Structured Credit CRM.
-- It is designed for Databricks SQL and Delta Lake.
-- It is idempotent and can be re-run safely, using `CREATE TABLE IF NOT EXISTS`.

-- Create the schema if it doesn't exist to ensure the script is self-contained.
CREATE SCHEMA IF NOT EXISTS cri_cra_dev.crm;
USE cri_cra_dev.crm;

-- ====================================================================
-- SECTION 1: CORE ENTITIES
-- These tables represent the main objects in the CRM.
-- ====================================================================

-- Tabela de Operações: Armazena a informação central de cada operação de crédito.
CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name STRING NOT NULL COMMENT 'Nome único da operação.',
    area STRING NOT NULL COMMENT 'Área de negócio responsável (ex: CRI, Capital Solutions).',
    operation_type STRING NOT NULL COMMENT 'Tipo da operação (ex: CRI, CRA, Debênture).',
    maturity_date TIMESTAMP NOT NULL COMMENT 'Data de vencimento da operação.',
    responsible_analyst STRING NOT NULL COMMENT 'Nome do analista responsável.',
    
    -- Frequências de monitoramento
    review_frequency STRING NOT NULL COMMENT 'Frequência da Revisão Gerencial (ex: Trimestral).',
    call_frequency STRING NOT NULL COMMENT 'Frequência das calls de acompanhamento.',
    df_frequency STRING NOT NULL COMMENT 'Frequência de análise de DFs e Dívida.',
    
    -- Classificação e Status
    segmento STRING COMMENT 'Segmento de mercado da operação.',
    rating_operation STRING NOT NULL COMMENT 'Rating atual da operação.',
    rating_group STRING NOT NULL COMMENT 'Rating atual do grupo econômico.',
    watchlist STRING NOT NULL COMMENT 'Status no watchlist (Verde, Amarelo, Vermelho).',
    
    -- Covenants
    ltv FLOAT COMMENT 'Covenant de Loan to Value.',
    dscr FLOAT COMMENT 'Covenant de Debt Service Coverage Ratio.',
    
    -- Flags de Monitoramento Padrão
    monitoring_news BOOLEAN,
    monitoring_fii_report BOOLEAN,
    monitoring_operational_info BOOLEAN,
    monitoring_receivables_portfolio BOOLEAN,
    monitoring_construction_report BOOLEAN,
    monitoring_commercial_info BOOLEAN,
    monitoring_spe_dfs BOOLEAN
) COMMENT 'Tabela principal contendo todas as operações de crédito estruturado.';

-- Tabela de Projetos: Entidades (imóveis, empreendimentos) associadas às operações.
CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name STRING NOT NULL
) COMMENT 'Repositório de projetos (imóveis, etc.) vinculados às operações.';

-- Tabela de Garantias: Tipos de garantias que podem ser associadas às operações.
CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.guarantees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name STRING NOT NULL
) COMMENT 'Repositório de tipos de garantias para as operações.';


-- ====================================================================
-- SECTION 2: RELATIONSHIP (JOIN) TABLES
-- These tables manage the many-to-many relationships.
-- ====================================================================

-- Tabela de Junção: Operações <-> Projetos
CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operation_projects (
    operation_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    PRIMARY KEY (operation_id, project_id),
    FOREIGN KEY (operation_id) REFERENCES cri_cra_dev.crm.operations(id),
    FOREIGN KEY (project_id) REFERENCES cri_cra_dev.crm.projects(id)
) COMMENT 'Tabela de ligação para a relação N-N entre operações e projetos.';

-- Tabela de Junção: Operações <-> Garantias
CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operation_guarantees (
    operation_id BIGINT NOT NULL,
    guarantee_id BIGINT NOT NULL,
    PRIMARY KEY (operation_id, guarantee_id),
    FOREIGN KEY (operation_id) REFERENCES cri_cra_dev.crm.operations(id),
    FOREIGN KEY (guarantee_id) REFERENCES cri_cra_dev.crm.guarantees(id)
) COMMENT 'Tabela de ligação para a relação N-N entre operações e garantias.';


-- ====================================================================
-- SECTION 3: ACTIVITY & HISTORY TABLES
-- These tables track events, tasks, and historical changes.
-- ====================================================================

-- Tabela de Eventos: Registra todos os acontecimentos de uma operação.
CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT NOT NULL,
    date TIMESTAMP NOT NULL,
    type STRING NOT NULL,
    title STRING NOT NULL,
    description STRING NOT NULL,
    registered_by STRING NOT NULL,
    next_steps STRING,
    completed_task_id STRING COMMENT 'ID da tarefa que este evento concluiu.',
    FOREIGN KEY (operation_id) REFERENCES cri_cra_dev.crm.operations(id)
) COMMENT 'Registra todos os eventos (reuniões, calls, etc.) associados a uma operação.';

-- Tabela de Regras de Tarefas: Define a geração de tarefas recorrentes ou pontuais.
CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.task_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT NOT NULL,
    name STRING NOT NULL,
    frequency STRING NOT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    description STRING,
    priority STRING,
    FOREIGN KEY (operation_id) REFERENCES cri_cra_dev.crm.operations(id)
) COMMENT 'Define as regras para a geração automática de tarefas.';

-- Tabela de Histórico de Ratings: Guarda o histórico de alterações de rating, watchlist e sentimento.
CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.rating_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT NOT NULL,
    date TIMESTAMP NOT NULL,
    rating_operation STRING NOT NULL,
    rating_group STRING NOT NULL,
    watchlist STRING NOT NULL,
    sentiment STRING NOT NULL,
    event_id BIGINT,
    FOREIGN KEY (operation_id) REFERENCES cri_cra_dev.crm.operations(id)
    -- A FK para event_id é omitida intencionalmente para evitar dependência cíclica e permitir
    -- que o histórico seja criado antes do evento em algumas lógicas de transação. A ligação é lógica.
) COMMENT 'Mantém um registro histórico de todas as mudanças de rating e watchlist.';


-- ====================================================================
-- SECTION 4: SYSTEM & UTILITY TABLES
-- These tables support application-level features like logging and exceptions.
-- ====================================================================

-- Tabela de Exceções de Tarefas: Armazena tarefas deletadas para não serem recriadas.
CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.task_exceptions (
    task_id STRING PRIMARY KEY,
    operation_id BIGINT NOT NULL,
    deleted_at TIMESTAMP NOT NULL,
    deleted_by STRING NOT NULL,
    FOREIGN KEY (operation_id) REFERENCES cri_cra_dev.crm.operations(id)
) COMMENT 'Registra tarefas que foram manualmente deletadas para que o sistema não as gere novamente.';

-- Tabela de Logs de Auditoria: Registra todas as ações de CRUD no sistema.
CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    user_name STRING NOT NULL,
    action STRING NOT NULL COMMENT 'Ação realizada: CREATE, UPDATE, DELETE.',
    entity_type STRING NOT NULL COMMENT 'Tipo da entidade afetada: Operation, Event, etc.',
    entity_id STRING NOT NULL COMMENT 'ID da entidade afetada.',
    details STRING COMMENT 'Descrição detalhada da alteração.'
) COMMENT 'Trilha de auditoria para todas as modificações de dados no CRM.';

-- Tabela de Notas de Revisão: Armazena notas editáveis para o painel de Revisão de Crédito.
CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operation_review_notes (
    operation_id BIGINT PRIMARY KEY,
    notes STRING,
    updated_at TIMESTAMP NOT NULL,
    updated_by STRING NOT NULL,
    FOREIGN KEY (operation_id) REFERENCES cri_cra_dev.crm.operations(id)
) COMMENT 'Armazena notas e observações editáveis para cada operação, usadas no painel de Revisão de Crédito.';
