
-- CRM Schema Update Script
-- This script updates an existing database schema to the latest version.
-- It is designed to be safely re-runnable on Databricks SQL.
-- It uses `ADD COLUMN IF NOT EXISTS` and `CREATE TABLE IF NOT EXISTS` to prevent errors.

USE cri_cra_dev.crm;

-- ====================================================================
-- Tabela: operations
-- Garante que a tabela principal de operações tenha todas as colunas necessárias.
-- ====================================================================
ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN IF NOT EXISTS area STRING;
ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN IF NOT EXISTS operation_type STRING;
ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN IF NOT EXISTS maturity_date TIMESTAMP;
ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN IF NOT EXISTS responsible_analyst STRING;
ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN IF NOT EXISTS review_frequency STRING;
ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN IF NOT EXISTS call_frequency STRING;
ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN IF NOT EXISTS df_frequency STRING;
ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN IF NOT EXISTS segmento STRING;
ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN IF NOT EXISTS rating_operation STRING;
ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN IF NOT EXISTS rating_group STRING;
ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN IF NOT EXISTS watchlist STRING;
ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN IF NOT EXISTS ltv FLOAT;
ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN IF NOT EXISTS dscr FLOAT;
ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN IF NOT EXISTS monitoring_news BOOLEAN;
ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN IF NOT EXISTS monitoring_fii_report BOOLEAN;
ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN IF NOT EXISTS monitoring_operational_info BOOLEAN;
ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN IF NOT EXISTS monitoring_receivables_portfolio BOOLEAN;
ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN IF NOT EXISTS monitoring_construction_report BOOLEAN;
ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN IF NOT EXISTS monitoring_commercial_info BOOLEAN;
ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN IF NOT EXISTS monitoring_spe_dfs BOOLEAN;

-- Nota sobre valores padrão:
-- No Databricks SQL, ALTER TABLE não suporta definir um valor DEFAULT diretamente.
-- Se precisar popular campos 'area' nulos existentes, execute separadamente:
-- UPDATE cri_cra_dev.crm.operations SET area = 'CRI' WHERE area IS NULL;

-- ====================================================================
-- Tabela: events
-- Adiciona a coluna para vincular um evento a uma tarefa concluída.
-- ====================================================================
ALTER TABLE cri_cra_dev.crm.events ADD COLUMN IF NOT EXISTS completed_task_id STRING;

-- ====================================================================
-- Tabela: rating_history
-- Adiciona colunas para vincular o histórico a um evento e para rastrear o status do watchlist e sentimento.
-- ====================================================================
ALTER TABLE cri_cra_dev.crm.rating_history ADD COLUMN IF NOT EXISTS event_id BIGINT;
ALTER TABLE cri_cra_dev.crm.rating_history ADD COLUMN IF NOT EXISTS watchlist STRING;
ALTER TABLE cri_cra_dev.crm.rating_history ADD COLUMN IF NOT EXISTS sentiment STRING;


-- ====================================================================
-- Tabela: task_exceptions
-- Cria a tabela para permitir que os usuários excluam tarefas permanentemente.
-- ====================================================================
CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.task_exceptions (
    task_id STRING PRIMARY KEY,
    operation_id BIGINT,
    deleted_at TIMESTAMP,
    deleted_by STRING
);

-- ====================================================================
-- Tabela: audit_logs
-- Cria a tabela para fornecer um histórico completo de todas as alterações no sistema.
-- ====================================================================
CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP,
    user_name STRING,
    action STRING, -- e.g., 'CREATE', 'UPDATE', 'DELETE'
    entity_type STRING, -- e.g., 'Operation', 'TaskRule', 'Event'
    entity_id STRING, -- Pode ser BIGINT (para a maioria dos IDs) ou STRING (para IDs de tarefas)
    details STRING -- Descrição legível da alteração
);

-- ====================================================================
-- Tabela: operation_review_notes
-- Cria a tabela para armazenar observações editáveis para operações.
-- ====================================================================
CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operation_review_notes (
    operation_id BIGINT PRIMARY KEY,
    notes STRING,
    updated_at TIMESTAMP,
    updated_by STRING
);
